# Generated by Django 2.2.1 on 2019-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=300)),
                ('host_ip', models.CharField(max_length=20)),
            ],
        ),
    ]
